Scenario:
  - name: Login
    url: https://assist9.i-on.net/login
    type: login
  - name: Healthcare
    url: https://assist9.i-on.net/rb/main#booking/calendar?resourceId=555a0f1645cee1e334430183
    type: booking
  - name: Lunch
    url: https://assist9.i-on.net/rb/main#booking/calendar?resourceId=554971d845ceac19504bbe46
    type: booking
